// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1yqaIuzIiT_NyGFMDJbH9-j4PLxyunho',
    appId: '1:1013405459199:android:0336b4f3e966c20ac362ca',
    messagingSenderId: '1013405459199',
    projectId: 'fir-flutter-app-632ad',
    storageBucket: 'fir-flutter-app-632ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWGEh-MK4qmTn-LSG2Llv1HyIlC-_XqmA',
    appId: '1:1013405459199:ios:c4ce1ccaa86c2c44c362ca',
    messagingSenderId: '1013405459199',
    projectId: 'fir-flutter-app-632ad',
    storageBucket: 'fir-flutter-app-632ad.firebasestorage.app',
    iosBundleId: 'com.example.firebaseFlutterApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7ikoR4qiIc7TkSBzuugW739sTnGQeGHE',
    appId: '1:1013405459199:web:e75ce7b6839cdae1c362ca',
    messagingSenderId: '1013405459199',
    projectId: 'fir-flutter-app-632ad',
    authDomain: 'fir-flutter-app-632ad.firebaseapp.com',
    storageBucket: 'fir-flutter-app-632ad.firebasestorage.app',
    measurementId: 'G-RETRVGF4EQ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWGEh-MK4qmTn-LSG2Llv1HyIlC-_XqmA',
    appId: '1:1013405459199:ios:c4ce1ccaa86c2c44c362ca',
    messagingSenderId: '1013405459199',
    projectId: 'fir-flutter-app-632ad',
    storageBucket: 'fir-flutter-app-632ad.firebasestorage.app',
    iosBundleId: 'com.example.firebaseFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7ikoR4qiIc7TkSBzuugW739sTnGQeGHE',
    appId: '1:1013405459199:web:d159b0be8860925fc362ca',
    messagingSenderId: '1013405459199',
    projectId: 'fir-flutter-app-632ad',
    authDomain: 'fir-flutter-app-632ad.firebaseapp.com',
    storageBucket: 'fir-flutter-app-632ad.firebasestorage.app',
    measurementId: 'G-5J3LQLFR1F',
  );

}